# Generated by Django 5.2.5 on 2025-08-14 08:48

from django.db import migrations
from django.contrib.auth.models import User


def create_admin_user(apps, schema_editor):
    """Create admin user if it doesn't exist"""
    if not User.objects.filter(username="admin").exists():
        User.objects.create_superuser(
            username="admin", email="admin@example.com", password="admin"
        )


def remove_admin_user(apps, schema_editor):
    """Remove admin user"""
    User.objects.filter(username="admin").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("youtube", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_admin_user, remove_admin_user),
    ]
